/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Main */

#ifndef _Included_org_example_Main
#define _Included_org_example_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Main
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_Main_hello
  (JNIEnv *, jclass);

/*
 * Class:     org_example_Main
 * Method:    changeGovnishe
 * Signature: (Lorg/example/Main/Govnishe;F)V
 */
JNIEXPORT void JNICALL Java_org_example_Main_changeGovnishe
  (JNIEnv *, jclass, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
