/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Main_PoolAllocator */

#ifndef _Included_org_example_Main_PoolAllocator
#define _Included_org_example_Main_PoolAllocator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Main_PoolAllocator
 * Method:    create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_example_Main_00024PoolAllocator_create
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
