/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_NativeControl */

#ifndef _Included_org_example_NativeControl
#define _Included_org_example_NativeControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_NativeControl
 * Method:    freeVec3Allocator
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_example_NativeControl_freeVec3Allocator
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
