/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Main_Vector3f */

#ifndef _Included_org_example_Main_Vector3f
#define _Included_org_example_Main_Vector3f
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Main_Vector3f
 * Method:    doCrazy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_Main_00024Vector3f_doCrazy
  (JNIEnv *, jobject);

/*
 * Class:     org_example_Main_Vector3f
 * Method:    create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_example_Main_00024Vector3f_create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_example_Main_Vector3f
 * Method:    n_memFree
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_example_Main_00024Vector3f_n_1memFree
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_example_Main_Vector3f
 * Method:    n_x
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_example_Main_00024Vector3f_n_1x__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_example_Main_Vector3f
 * Method:    n_x
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_example_Main_00024Vector3f_n_1x__JF
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_example_Main_Vector3f
 * Method:    n_y
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_example_Main_00024Vector3f_n_1y__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_example_Main_Vector3f
 * Method:    n_y
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_example_Main_00024Vector3f_n_1y__JF
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_example_Main_Vector3f
 * Method:    n_z
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_example_Main_00024Vector3f_n_1z__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_example_Main_Vector3f
 * Method:    n_z
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_example_Main_00024Vector3f_n_1z__JF
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_example_Main_Vector3f
 * Method:    n_x_y_z
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_org_example_Main_00024Vector3f_n_1x_1y_1z
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
